### ISSUE TITLE
Declaring multiple instances within forms is inconsistent

### ISSUE THREAD

**Issue by Fannon** [Fannon/mobo#10]
```yaml
items:
  - $extend: /model/SingleInstance
  - items:
      $extend: /model/MultipleInstance
```

Should be ?

```yaml
items:
  - $extend: /model/SingleInstance
  - items:
      - $extend: /model/MultipleInstance
```
