### ISSUE TITLE
How to use smw_appendPage?

### ISSUE THREAD

**Issue by cwillmes** [Fannon/mobo#20]
Hi,

I have a  '/model/Topic' looking like this:
```
title: Topic
description: A topic category

items:
  - $extend: /field/Description


smw_appendPage: 
  template: 
    - topic-query-ask
```

What I basically want is, that on each Topic page a query is rendered. For this I defined a Template, in 'smw_query/topic-query.ask', looking like this:

```
{{#ask:
[[Category:Dataset]] [[Topic::{{FULLPAGENAME}}]]
|?Source
|?Abstract
|?Temporal
|?Spatial
|?Topic
|?DatasetURL
|?Resources
|?Bibliography
|format=broadtable
}}
```

I get the following error:
`[E] /model/Topic.yaml references to non exisiting template: topic-query-ask`

The template {{topic-query-ask}} exists.

How do I reference the template correctly?
